# Generated by Django 5.0.2 on 2024-03-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
                ('category_image_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100)),
                ('division_unique_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'division',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_license_number', models.CharField(max_length=50, null=True)),
                ('store_rating', models.IntegerField(default=5)),
                ('store_desription', models.TextField()),
                ('store_image_url', models.TextField()),
                ('store_open_dates', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(default=0, max_length=10)),
                ('isBlocked', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('shopowner', 'shopowner'), ('menuitadmin', 'menutitadmin'), ('customer', 'customer')], default='shopowner', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unique_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_rating', models.IntegerField(default=5)),
                ('product_description', models.TextField()),
                ('product_image_url', models.TextField()),
                ('product_available', models.IntegerField(default=0)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('product_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.division')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='division',
            name='division_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores'),
        ),
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_unique_id', models.CharField(max_length=50)),
                ('ad_type', models.CharField(choices=[('banner', 'banner'), ('video', 'video')], max_length=50)),
                ('ad_url', models.TextField()),
                ('ad_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
        ),
        migrations.AddField(
            model_name='stores',
            name='store_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
