# Generated by Django 5.0.2 on 2024-03-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.stores'),
            preserve_default=False,
        ),
    ]
