# Generated by Django 5.0.2 on 2024-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisments',
            name='ad_name',
            field=models.CharField(default='ad', max_length=50),
        ),
    ]
