# Generated by Django 5.0.2 on 2024-03-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_advertisments_ad_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
